### ISSUE TITLE
Programs and macros to output CSVs for website

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/Web#12]

**Comment by rpitingolo** [comment]
@lhendey I'm having trouble coming up with a label for variables like PctChgTotPop now that we've changed the timeframe to be the ending year. I can't use "Change past 10 years" because that doesn't work for ACS change variables (like 2000 - 2012-16 foreign born). But I can't use "change since last decennial census because that would imply 2010 - 2012-16. Any ideas?

**Comment by lhendey** [comment]
@Pitingolo, Rob (RPitingolo@urban.org)<mailto:RPitingolo@urban.org> “Change since 2000”?

**Comment by rpitingolo** [comment]
@lhendey we also have 1990-2000 change indicators.

**Comment by lhendey** [comment]
@Pitingolo, Rob (RPitingolo@urban.org)<mailto:RPitingolo@urban.org> are they all the same var? Could that be “change since 1990?”

**Comment by rpitingolo** [comment]
@lhendey on the explorer now we have indicators like "% change population" "% change child population". I think the only way to get this to work would be to split them, so it would now be "% child population 1990-2000" "% child population since 2000" and the timeframe would be 2000 and 2010 respectively, so that they show up correctly in the table. 

Kind of messy, but gets the job done.
