### ISSUE TITLE
Add update message to NIDC web site home page

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Web#15]
@rpitingolo Please put it on your to do list to create a new home page for the NIDC website that contains the following announcement: “NeighborhoodInfo DC will be retired on May 1, 2018, but you can find our data and reports about the District and the region on our new Urban: Greater DC website <link to new site>. Thank you to all our supporters!”

This announcement should be prominent so that people visiting the site don't miss it. The announcement should go up on the homepage on the official launch date for the new site, **April 4**. 

cc: @lhendey

**Comment by lhendey** [comment]
@rpitingolo - this update now needs to occur on April 11. cc @ptatian

**Comment by lhendey** [comment]
@rpitingolo - can you do this today and remove the twitter feed? I believe the newsletter is going out early tomorrow morning.

**Comment by rpitingolo** [comment]
@lhendey OK. Working on this.

**Comment by rpitingolo** [comment]
@lhendey updated. Look OK?

**Comment by lhendey** [comment]
Yes, thanks.

**Comment by lhendey** [comment]
I forgot – the punctuation is a en-dash not a colon….

From: Hendey, Leah
Sent: Tuesday, April 10, 2018 3:37 PM
To: 'NeighborhoodInfoDC/Web' <reply@reply.github.com>; NeighborhoodInfoDC/Web <Web@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [NeighborhoodInfoDC/Web] Add update message to NIDC web site home page (#15)

Yes, thanks.

**Comment by rpitingolo** [comment]
@lhendey ok, fixed it.
